### ISSUE TITLE
Remove underline from apply link.

### ISSUE THREAD

**Issue by illegalprime** [HackGT/hackgt4#6]
Could you add
```css
a {
    text-decoration: none;
}
```
to the 'apply now' button? (so the underline goes away).
